- gather_facts: false
  hosts: master
  remote_user: xxx
  tasks:

  - name: Ping
    ansible.builtin.ping:

  - name: Создание каталогов
    ansible.builtin.file:
      mode: '0755'
      path: '{{ item }}'
      state: directory
    loop:
      - ~/python

  - name: Копирование
    ansible.posix.synchronize:
      src: '{{ item }}'
      dest: ~/python/
      delete: true
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=miranda.egg-info"
        - "--exclude=miranda/miranda/"
    loop:
      - ~/Documents/python/miranda
      - ~/Documents/python/tools

  - name: Копирование каталога server
    ansible.posix.synchronize:
      src: ~/Documents/enterprise/server
      dest: ~/
      delete: true
